theme: jekyll-theme-minimal
title: Ayaan Miah's homepage
description: Ayaan Miah's personal homepage. 
             I am a 5th grader currently studying in Hickory Grove Elementary School, Located in Peoria, IL, USA. I am interested in programming, technology, and science. This website is a place for me to share my projects, ideas, and interests with the world.
